# Permalinks
permalink:           pretty

# Setup
title:               Ka's github blog
tagline:             A Moderately Okay Data Science Blog
url:                 http://khsio.github.io/
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ka Hou Sio
  url:               https://www.linkedin.com/in/kahousio/
  email:             kahousio@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/khsio

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
